export const IDS = {
  landing: {
    getStarted: 'landing-get-started-btn',
    heroTitle: 'landing-hero-title',
    googleLogin: 'landing-google-login-btn',
  },
  dashboard: {
    root: 'dashboard-root',
    ieaCard: 'iea-card',
    ieaScore: 'iea-score',
    pillar: (key) => `iea-pillar-${key}`,
    missionsList: 'missions-list',
    mission: (id) => `mission-${id}`,
    missionComplete: (id) => `mission-complete-${id}`,
    missionSkip: (id) => `mission-skip-${id}`,
    regenerate: 'missions-regenerate-btn',
    startCheckin: 'start-checkin-btn',
    moodEmoji: (v) => `mood-emoji-${v}`,
    streakBadge: 'streak-badge',
    logout: 'nav-logout',
    // Redesign iteration 5
    primaryCta: 'primary-cta-what-now',
    recommendation: 'recommendation-card',
    recommendationTitle: 'recommendation-title',
    confidence: 'recommendation-confidence',
    radar: 'radar-section',
    toggleAlternates: 'toggle-alternates',
  },
  checkin: {
    root: 'checkin-root',
    sleepInput: 'checkin-sleep-input',
    energy: (v) => `checkin-energy-${v}`,
    mood: (v) => `checkin-mood-${v}`,
    stress: (v) => `checkin-stress-${v}`,
    upcomingYes: 'checkin-upcoming-yes',
    upcomingNo: 'checkin-upcoming-no',
    examName: 'checkin-exam-name',
    examDate: 'checkin-exam-date',
    onCallYes: 'checkin-oncall-yes',
    onCallNo: 'checkin-oncall-no',
    commitments: 'checkin-commitments',
    freeText: 'checkin-freetext',
    submit: 'checkin-submit-btn',
    next: 'checkin-next-btn',
    back: 'checkin-back-btn',
  },
  history: { root: 'history-root' },
  mindfulness: {
    root: 'mindfulness-root',
    play: (slug) => `mindfulness-play-${slug}`,
    complete: 'mindfulness-complete-btn',
  },
  subjects: {
    root: 'subjects-root',
    name: 'subject-name-input',
    depToggle: 'subject-dependency-toggle',
    save: 'subject-save-btn',
    remove: (id) => `subject-remove-${id}`,
    examName: 'exam-name-input',
    examDate: 'exam-date-input',
    examSubject: 'exam-subject-select',
    examSave: 'exam-save-btn',
    gradeInput: (id) => `exam-grade-${id}`,
    gradeSave: (id) => `exam-grade-save-${id}`,
    examRemove: (id) => `exam-remove-${id}`,
  },
  badges: { root: 'badges-root', item: (slug) => `badge-${slug}` },
  resources: { root: 'resources-root', item: (slug) => `resource-${slug}` },
  support: {
    root: 'support-root',
    item: (slug) => `support-contact-${slug}`,
    call: (slug) => `support-call-${slug}`,
    chat: (slug) => `support-chat-${slug}`,
    link: (slug) => `support-link-${slug}`,
    dashboardBanner: 'support-dashboard-banner',
  },
  mentalHealth: {
    overlay: 'mh-alert-overlay',
    overlayCallCvv: 'mh-alert-call-cvv',
    overlayCallSamu: 'mh-alert-call-samu',
    overlaySeeSupport: 'mh-alert-see-support',
    overlayDismiss: 'mh-alert-dismiss',
    dashboardCard: 'mh-alert-dashboard-card',
    dashboardCardAck: 'mh-alert-dashboard-ack',
  },
  settings: {
    root: 'settings-root',
    mode: (m) => `mode-${m}`,
    studyTool: (t) => `study-tool-${t}`,
  },
};

export default IDS;
